//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascension_Calculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OPTIONS_DISPLAYPANELBACKGROUNDS {
            get {
                return ((bool)(this["OPTIONS_DISPLAYPANELBACKGROUNDS"]));
            }
            set {
                this["OPTIONS_DISPLAYPANELBACKGROUNDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OPTIONS_CHECKFORUPDATES {
            get {
                return ((bool)(this["OPTIONS_CHECKFORUPDATES"]));
            }
            set {
                this["OPTIONS_CHECKFORUPDATES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OPTIONS_SHOWLISTGROUPS {
            get {
                return ((bool)(this["OPTIONS_SHOWLISTGROUPS"]));
            }
            set {
                this["OPTIONS_SHOWLISTGROUPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 90, 90")]
        public global::System.Drawing.Color OPTIONS_EXPORTGRADIENTLEFT {
            get {
                return ((global::System.Drawing.Color)(this["OPTIONS_EXPORTGRADIENTLEFT"]));
            }
            set {
                this["OPTIONS_EXPORTGRADIENTLEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16, 16, 16")]
        public global::System.Drawing.Color OPTIONS_EXPORTGRADIENTRIGHT {
            get {
                return ((global::System.Drawing.Color)(this["OPTIONS_EXPORTGRADIENTRIGHT"]));
            }
            set {
                this["OPTIONS_EXPORTGRADIENTRIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPTIONS_EXPORTBACKGROUND {
            get {
                return ((string)(this["OPTIONS_EXPORTBACKGROUND"]));
            }
            set {
                this["OPTIONS_EXPORTBACKGROUND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OPTIONS_PANELSTALENTSABILITIES {
            get {
                return ((bool)(this["OPTIONS_PANELSTALENTSABILITIES"]));
            }
            set {
                this["OPTIONS_PANELSTALENTSABILITIES"] = value;
            }
        }
    }
}
